{{- if and .Values.roundcube.enabled .Values.roundcube.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mail-platform.fullname" . }}-roundcube
  labels:
    {{- include "mail-platform.roundcube.labels" . | nindent 4 }}
  {{- with .Values.roundcube.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.roundcube.ingress.className }}
  ingressClassName: {{ .Values.roundcube.ingress.className }}
  {{- end }}
  {{- if .Values.roundcube.ingress.tls }}
  tls:
    {{- range .Values.roundcube.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.roundcube.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mail-platform.fullname" $ }}-roundcube
                port:
                  number: {{ $.Values.roundcube.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
